component_depth: 1
languages:
- java
exclude:
- ./aspectjrt1.6.9/.*
- ./aspectjrt1.6.9/META-INF/.*
- ./aspectjrt1.6.9/org/.*
- ./aspectjrt1.6.9/org/aspectj/.*
- ./aspectjrt1.6.9/org/aspectj/internal/.*
- ./aspectjrt1.6.9/org/aspectj/internal/lang/.*
- ./aspectjrt1.6.9/org/aspectj/internal/lang/annotation/.*
- ./aspectjrt1.6.9/org/aspectj/internal/lang/reflect/.*
- ./aspectjrt1.6.9/org/aspectj/lang/.*
- ./aspectjrt1.6.9/org/aspectj/lang/annotation/.*
- ./aspectjrt1.6.9/org/aspectj/lang/reflect/.*
- ./aspectjrt1.6.9/org/aspectj/runtime/.*
- ./aspectjrt1.6.9/org/aspectj/runtime/internal/.*
- ./aspectjrt1.6.9/org/aspectj/runtime/internal/cflowstack/.*
- ./aspectjrt1.6.9/org/aspectj/runtime/reflect/.*
- ./aspectjtools1.6.9/.*
- ./aspectjtools1.6.9/META-INF/.*
- ./aspectjtools1.6.9/airpdata/.*
- ./aspectjtools1.6.9/bin/.*
- ./aspectjtools1.6.9/bin/META-INF/.*
- ./aspectjtools1.6.9/bin/airpdata/.*
- ./aspectjtools1.6.9/bin/lib/.*
- ./aspectjtools1.6.9/bin/org/.*
- ./aspectjtools1.6.9/bin/org/aspectj/.*
- ./aspectjtools1.6.9/bin/org/aspectj/ajde/.*
- ./aspectjtools1.6.9/bin/org/aspectj/ajde/core/.*
- ./aspectjtools1.6.9/bin/org/aspectj/ajde/core/internal/.*
- ./aspectjtools1.6.9/bin/org/aspectj/ajde/internal/.*
- ./aspectjtools1.6.9/bin/org/aspectj/ajde/ui/.*
- ./aspectjtools1.6.9/bin/org/aspectj/ajde/ui/internal/.*
- ./aspectjtools1.6.9/bin/org/aspectj/ajde/ui/javaoptions/.*
- ./aspectjtools1.6.9/bin/org/aspectj/ajde/ui/swing/.*
- ./aspectjtools1.6.9/bin/org/aspectj/ajdt/.*
- ./aspectjtools1.6.9/bin/org/aspectj/ajdt/ajc/.*
- ./aspectjtools1.6.9/bin/org/aspectj/ajdt/compiler/.*
- ./aspectjtools1.6.9/bin/org/aspectj/ajdt/core/.*
- ./aspectjtools1.6.9/bin/org/aspectj/ajdt/core/dom/.*
- ./aspectjtools1.6.9/bin/org/aspectj/ajdt/internal/.*
- ./aspectjtools1.6.9/bin/org/aspectj/ajdt/internal/compiler/.*
- ./aspectjtools1.6.9/bin/org/aspectj/ajdt/internal/compiler/ast/.*
- ./aspectjtools1.6.9/bin/org/aspectj/ajdt/internal/compiler/lookup/.*
- ./aspectjtools1.6.9/bin/org/aspectj/ajdt/internal/compiler/parser/.*
- ./aspectjtools1.6.9/bin/org/aspectj/ajdt/internal/compiler/problem/.*
- ./aspectjtools1.6.9/bin/org/aspectj/ajdt/internal/core/.*
- ./aspectjtools1.6.9/bin/org/aspectj/ajdt/internal/core/builder/.*
- ./aspectjtools1.6.9/bin/org/aspectj/apache/.*
- ./aspectjtools1.6.9/bin/org/aspectj/apache/bcel/.*
- ./aspectjtools1.6.9/bin/org/aspectj/apache/bcel/classfile/.*
- ./aspectjtools1.6.9/bin/org/aspectj/apache/bcel/classfile/annotation/.*
- ./aspectjtools1.6.9/bin/org/aspectj/apache/bcel/generic/.*
- ./aspectjtools1.6.9/bin/org/aspectj/apache/bcel/util/.*
- ./aspectjtools1.6.9/bin/org/aspectj/asm/.*
- ./aspectjtools1.6.9/bin/org/aspectj/asm/internal/.*
- ./aspectjtools1.6.9/bin/org/aspectj/bridge/.*
- ./aspectjtools1.6.9/bin/org/aspectj/bridge/context/.*
- ./aspectjtools1.6.9/bin/org/aspectj/lang/.*
- ./aspectjtools1.6.9/bin/org/aspectj/lang/internal/.*
- ./aspectjtools1.6.9/bin/org/aspectj/lang/internal/lang/.*
- ./aspectjtools1.6.9/bin/org/aspectj/lang/reflect/.*
- ./aspectjtools1.6.9/bin/org/aspectj/org/.*
- ./aspectjtools1.6.9/bin/org/aspectj/org/eclipse/.*
- ./aspectjtools1.6.9/bin/org/aspectj/org/eclipse/jdt/.*
- ./aspectjtools1.6.9/bin/org/aspectj/org/eclipse/jdt/core/.*
- ./aspectjtools1.6.9/bin/org/aspectj/org/eclipse/jdt/core/compiler/.*
- ./aspectjtools1.6.9/bin/org/aspectj/org/eclipse/jdt/core/dom/.*
- ./aspectjtools1.6.9/bin/org/aspectj/org/eclipse/jdt/core/dom/rewrite/.*
- ./aspectjtools1.6.9/bin/org/aspectj/org/eclipse/jdt/core/eval/.*
- ./aspectjtools1.6.9/bin/org/aspectj/org/eclipse/jdt/core/formatter/.*
- ./aspectjtools1.6.9/bin/org/aspectj/org/eclipse/jdt/core/jdom/.*
- ./aspectjtools1.6.9/bin/org/aspectj/org/eclipse/jdt/core/search/.*
- ./aspectjtools1.6.9/bin/org/aspectj/org/eclipse/jdt/core/util/.*
- ./aspectjtools1.6.9/bin/org/aspectj/org/eclipse/jdt/internal/.*
- ./aspectjtools1.6.9/bin/org/aspectj/org/eclipse/jdt/internal/antadapter/.*
- ./aspectjtools1.6.9/bin/org/aspectj/org/eclipse/jdt/internal/codeassist/.*
- ./aspectjtools1.6.9/bin/org/aspectj/org/eclipse/jdt/internal/codeassist/complete/.*
- ./aspectjtools1.6.9/bin/org/aspectj/org/eclipse/jdt/internal/codeassist/impl/.*
- ./aspectjtools1.6.9/bin/org/aspectj/org/eclipse/jdt/internal/codeassist/select/.*
- ./aspectjtools1.6.9/bin/org/aspectj/org/eclipse/jdt/internal/compiler/.*
- ./aspectjtools1.6.9/bin/org/aspectj/org/eclipse/jdt/internal/compiler/ast/.*
- ./aspectjtools1.6.9/bin/org/aspectj/org/eclipse/jdt/internal/compiler/batch/.*
- ./aspectjtools1.6.9/bin/org/aspectj/org/eclipse/jdt/internal/compiler/classfmt/.*
- ./aspectjtools1.6.9/bin/org/aspectj/org/eclipse/jdt/internal/compiler/codegen/.*
- ./aspectjtools1.6.9/bin/org/aspectj/org/eclipse/jdt/internal/compiler/env/.*
- ./aspectjtools1.6.9/bin/org/aspectj/org/eclipse/jdt/internal/compiler/flow/.*
- ./aspectjtools1.6.9/bin/org/aspectj/org/eclipse/jdt/internal/compiler/impl/.*
- ./aspectjtools1.6.9/bin/org/aspectj/org/eclipse/jdt/internal/compiler/lookup/.*
- ./aspectjtools1.6.9/bin/org/aspectj/org/eclipse/jdt/internal/compiler/parser/.*
- ./aspectjtools1.6.9/bin/org/aspectj/org/eclipse/jdt/internal/compiler/parser/diagnose/.*
- ./aspectjtools1.6.9/bin/org/aspectj/org/eclipse/jdt/internal/compiler/problem/.*
- ./aspectjtools1.6.9/bin/org/aspectj/org/eclipse/jdt/internal/compiler/util/.*
- ./aspectjtools1.6.9/bin/org/aspectj/org/eclipse/jdt/internal/core/.*
- ./aspectjtools1.6.9/bin/org/aspectj/org/eclipse/jdt/internal/core/builder/.*
- ./aspectjtools1.6.9/bin/org/aspectj/org/eclipse/jdt/internal/core/dom/.*
- ./aspectjtools1.6.9/bin/org/aspectj/org/eclipse/jdt/internal/core/dom/rewrite/.*
- ./aspectjtools1.6.9/bin/org/aspectj/org/eclipse/jdt/internal/core/eval/.*
- ./aspectjtools1.6.9/bin/org/aspectj/org/eclipse/jdt/internal/core/hierarchy/.*
- ./aspectjtools1.6.9/bin/org/aspectj/org/eclipse/jdt/internal/core/index/.*
- ./aspectjtools1.6.9/bin/org/aspectj/org/eclipse/jdt/internal/core/jdom/.*
- ./aspectjtools1.6.9/bin/org/aspectj/org/eclipse/jdt/internal/core/search/.*
- ./aspectjtools1.6.9/bin/org/aspectj/org/eclipse/jdt/internal/core/search/indexing/.*
- ./aspectjtools1.6.9/bin/org/aspectj/org/eclipse/jdt/internal/core/search/matching/.*
- ./aspectjtools1.6.9/bin/org/aspectj/org/eclipse/jdt/internal/core/search/processing/.*
- ./aspectjtools1.6.9/bin/org/aspectj/org/eclipse/jdt/internal/core/util/.*
- ./aspectjtools1.6.9/bin/org/aspectj/org/eclipse/jdt/internal/eval/.*
- ./aspectjtools1.6.9/bin/org/aspectj/org/eclipse/jdt/internal/formatter/.*
- ./aspectjtools1.6.9/bin/org/aspectj/org/eclipse/jdt/internal/formatter/align/.*
- ./aspectjtools1.6.9/bin/org/aspectj/org/eclipse/jdt/internal/formatter/comment/.*
- ./aspectjtools1.6.9/bin/org/aspectj/org/eclipse/jdt/internal/formatter/old/.*
- ./aspectjtools1.6.9/bin/org/aspectj/runtime/.*
- ./aspectjtools1.6.9/bin/org/aspectj/runtime/internal/.*
- ./aspectjtools1.6.9/bin/org/aspectj/runtime/internal/cflowstack/.*
- ./aspectjtools1.6.9/bin/org/aspectj/runtime/reflect/.*
- ./aspectjtools1.6.9/bin/org/aspectj/tools/.*
- ./aspectjtools1.6.9/bin/org/aspectj/tools/ajc/.*
- ./aspectjtools1.6.9/bin/org/aspectj/tools/ajdoc/.*
- ./aspectjtools1.6.9/bin/org/aspectj/tools/ant/.*
- ./aspectjtools1.6.9/bin/org/aspectj/tools/ant/taskdefs/.*
- ./aspectjtools1.6.9/bin/org/aspectj/tools/ant/taskdefs/compilers/.*
- ./aspectjtools1.6.9/bin/org/aspectj/util/.*
- ./aspectjtools1.6.9/bin/org/aspectj/weaver/.*
- ./aspectjtools1.6.9/bin/org/aspectj/weaver/ast/.*
- ./aspectjtools1.6.9/bin/org/aspectj/weaver/bcel/.*
- ./aspectjtools1.6.9/bin/org/aspectj/weaver/bcel/asm/.*
- ./aspectjtools1.6.9/bin/org/aspectj/weaver/internal/.*
- ./aspectjtools1.6.9/bin/org/aspectj/weaver/internal/tools/.*
- ./aspectjtools1.6.9/bin/org/aspectj/weaver/loadtime/.*
- ./aspectjtools1.6.9/bin/org/aspectj/weaver/loadtime/definition/.*
- ./aspectjtools1.6.9/bin/org/aspectj/weaver/ltw/.*
- ./aspectjtools1.6.9/bin/org/aspectj/weaver/model/.*
- ./aspectjtools1.6.9/bin/org/aspectj/weaver/patterns/.*
- ./aspectjtools1.6.9/bin/org/aspectj/weaver/reflect/.*
- ./aspectjtools1.6.9/bin/org/aspectj/weaver/tools/.*
- ./aspectjtools1.6.9/lib/.*
- ./aspectjtools1.6.9/org/.*
- ./aspectjtools1.6.9/org/aspectj/.*
- ./aspectjtools1.6.9/org/aspectj/ajde/.*
- ./aspectjtools1.6.9/org/aspectj/ajde/core/.*
- ./aspectjtools1.6.9/org/aspectj/ajde/core/internal/.*
- ./aspectjtools1.6.9/org/aspectj/ajde/internal/.*
- ./aspectjtools1.6.9/org/aspectj/ajde/ui/.*
- ./aspectjtools1.6.9/org/aspectj/ajde/ui/internal/.*
- ./aspectjtools1.6.9/org/aspectj/ajde/ui/javaoptions/.*
- ./aspectjtools1.6.9/org/aspectj/ajde/ui/swing/.*
- ./aspectjtools1.6.9/org/aspectj/ajdt/.*
- ./aspectjtools1.6.9/org/aspectj/ajdt/ajc/.*
- ./aspectjtools1.6.9/org/aspectj/ajdt/compiler/.*
- ./aspectjtools1.6.9/org/aspectj/ajdt/core/.*
- ./aspectjtools1.6.9/org/aspectj/ajdt/core/dom/.*
- ./aspectjtools1.6.9/org/aspectj/ajdt/internal/.*
- ./aspectjtools1.6.9/org/aspectj/ajdt/internal/compiler/.*
- ./aspectjtools1.6.9/org/aspectj/ajdt/internal/compiler/ast/.*
- ./aspectjtools1.6.9/org/aspectj/ajdt/internal/compiler/lookup/.*
- ./aspectjtools1.6.9/org/aspectj/ajdt/internal/compiler/parser/.*
- ./aspectjtools1.6.9/org/aspectj/ajdt/internal/compiler/problem/.*
- ./aspectjtools1.6.9/org/aspectj/ajdt/internal/core/.*
- ./aspectjtools1.6.9/org/aspectj/ajdt/internal/core/builder/.*
- ./aspectjtools1.6.9/org/aspectj/apache/.*
- ./aspectjtools1.6.9/org/aspectj/apache/bcel/.*
- ./aspectjtools1.6.9/org/aspectj/apache/bcel/classfile/.*
- ./aspectjtools1.6.9/org/aspectj/apache/bcel/classfile/annotation/.*
- ./aspectjtools1.6.9/org/aspectj/apache/bcel/generic/.*
- ./aspectjtools1.6.9/org/aspectj/apache/bcel/util/.*
- ./aspectjtools1.6.9/org/aspectj/asm/.*
- ./aspectjtools1.6.9/org/aspectj/asm/internal/.*
- ./aspectjtools1.6.9/org/aspectj/bridge/.*
- ./aspectjtools1.6.9/org/aspectj/bridge/context/.*
- ./aspectjtools1.6.9/org/aspectj/lang/.*
- ./aspectjtools1.6.9/org/aspectj/lang/internal/.*
- ./aspectjtools1.6.9/org/aspectj/lang/internal/lang/.*
- ./aspectjtools1.6.9/org/aspectj/lang/reflect/.*
- ./aspectjtools1.6.9/org/aspectj/org/.*
- ./aspectjtools1.6.9/org/aspectj/org/eclipse/.*
- ./aspectjtools1.6.9/org/aspectj/org/eclipse/jdt/.*
- ./aspectjtools1.6.9/org/aspectj/org/eclipse/jdt/core/.*
- ./aspectjtools1.6.9/org/aspectj/org/eclipse/jdt/core/compiler/.*
- ./aspectjtools1.6.9/org/aspectj/org/eclipse/jdt/core/dom/.*
- ./aspectjtools1.6.9/org/aspectj/org/eclipse/jdt/core/dom/rewrite/.*
- ./aspectjtools1.6.9/org/aspectj/org/eclipse/jdt/core/eval/.*
- ./aspectjtools1.6.9/org/aspectj/org/eclipse/jdt/core/formatter/.*
- ./aspectjtools1.6.9/org/aspectj/org/eclipse/jdt/core/jdom/.*
- ./aspectjtools1.6.9/org/aspectj/org/eclipse/jdt/core/search/.*
- ./aspectjtools1.6.9/org/aspectj/org/eclipse/jdt/core/util/.*
- ./aspectjtools1.6.9/org/aspectj/org/eclipse/jdt/internal/.*
- ./aspectjtools1.6.9/org/aspectj/org/eclipse/jdt/internal/antadapter/.*
- ./aspectjtools1.6.9/org/aspectj/org/eclipse/jdt/internal/codeassist/.*
- ./aspectjtools1.6.9/org/aspectj/org/eclipse/jdt/internal/codeassist/complete/.*
- ./aspectjtools1.6.9/org/aspectj/org/eclipse/jdt/internal/codeassist/impl/.*
- ./aspectjtools1.6.9/org/aspectj/org/eclipse/jdt/internal/codeassist/select/.*
- ./aspectjtools1.6.9/org/aspectj/org/eclipse/jdt/internal/compiler/.*
- ./aspectjtools1.6.9/org/aspectj/org/eclipse/jdt/internal/compiler/ast/.*
- ./aspectjtools1.6.9/org/aspectj/org/eclipse/jdt/internal/compiler/batch/.*
- ./aspectjtools1.6.9/org/aspectj/org/eclipse/jdt/internal/compiler/classfmt/.*
- ./aspectjtools1.6.9/org/aspectj/org/eclipse/jdt/internal/compiler/codegen/.*
- ./aspectjtools1.6.9/org/aspectj/org/eclipse/jdt/internal/compiler/env/.*
- ./aspectjtools1.6.9/org/aspectj/org/eclipse/jdt/internal/compiler/flow/.*
- ./aspectjtools1.6.9/org/aspectj/org/eclipse/jdt/internal/compiler/impl/.*
- ./aspectjtools1.6.9/org/aspectj/org/eclipse/jdt/internal/compiler/lookup/.*
- ./aspectjtools1.6.9/org/aspectj/org/eclipse/jdt/internal/compiler/parser/.*
- ./aspectjtools1.6.9/org/aspectj/org/eclipse/jdt/internal/compiler/parser/diagnose/.*
- ./aspectjtools1.6.9/org/aspectj/org/eclipse/jdt/internal/compiler/problem/.*
- ./aspectjtools1.6.9/org/aspectj/org/eclipse/jdt/internal/compiler/util/.*
- ./aspectjtools1.6.9/org/aspectj/org/eclipse/jdt/internal/core/.*
- ./aspectjtools1.6.9/org/aspectj/org/eclipse/jdt/internal/core/builder/.*
- ./aspectjtools1.6.9/org/aspectj/org/eclipse/jdt/internal/core/dom/.*
- ./aspectjtools1.6.9/org/aspectj/org/eclipse/jdt/internal/core/dom/rewrite/.*
- ./aspectjtools1.6.9/org/aspectj/org/eclipse/jdt/internal/core/eval/.*
- ./aspectjtools1.6.9/org/aspectj/org/eclipse/jdt/internal/core/hierarchy/.*
- ./aspectjtools1.6.9/org/aspectj/org/eclipse/jdt/internal/core/index/.*
- ./aspectjtools1.6.9/org/aspectj/org/eclipse/jdt/internal/core/jdom/.*
- ./aspectjtools1.6.9/org/aspectj/org/eclipse/jdt/internal/core/search/.*
- ./aspectjtools1.6.9/org/aspectj/org/eclipse/jdt/internal/core/search/indexing/.*
- ./aspectjtools1.6.9/org/aspectj/org/eclipse/jdt/internal/core/search/matching/.*
- ./aspectjtools1.6.9/org/aspectj/org/eclipse/jdt/internal/core/search/processing/.*
- ./aspectjtools1.6.9/org/aspectj/org/eclipse/jdt/internal/core/util/.*
- ./aspectjtools1.6.9/org/aspectj/org/eclipse/jdt/internal/eval/.*
- ./aspectjtools1.6.9/org/aspectj/org/eclipse/jdt/internal/formatter/.*
- ./aspectjtools1.6.9/org/aspectj/org/eclipse/jdt/internal/formatter/align/.*
- ./aspectjtools1.6.9/org/aspectj/org/eclipse/jdt/internal/formatter/comment/.*
- ./aspectjtools1.6.9/org/aspectj/org/eclipse/jdt/internal/formatter/old/.*
- ./aspectjtools1.6.9/org/aspectj/runtime/.*
- ./aspectjtools1.6.9/org/aspectj/runtime/internal/.*
- ./aspectjtools1.6.9/org/aspectj/runtime/internal/cflowstack/.*
- ./aspectjtools1.6.9/org/aspectj/runtime/reflect/.*
- ./aspectjtools1.6.9/org/aspectj/tools/.*
- ./aspectjtools1.6.9/org/aspectj/tools/ajc/.*
- ./aspectjtools1.6.9/org/aspectj/tools/ajdoc/.*
- ./aspectjtools1.6.9/org/aspectj/tools/ant/.*
- ./aspectjtools1.6.9/org/aspectj/tools/ant/taskdefs/.*
- ./aspectjtools1.6.9/org/aspectj/tools/ant/taskdefs/compilers/.*
- ./aspectjtools1.6.9/org/aspectj/util/.*
- ./aspectjtools1.6.9/org/aspectj/weaver/.*
- ./aspectjtools1.6.9/org/aspectj/weaver/ast/.*
- ./aspectjtools1.6.9/org/aspectj/weaver/bcel/.*
- ./aspectjtools1.6.9/org/aspectj/weaver/bcel/asm/.*
- ./aspectjtools1.6.9/org/aspectj/weaver/internal/.*
- ./aspectjtools1.6.9/org/aspectj/weaver/internal/tools/.*
- ./aspectjtools1.6.9/org/aspectj/weaver/loadtime/.*
- ./aspectjtools1.6.9/org/aspectj/weaver/loadtime/definition/.*
- ./aspectjtools1.6.9/org/aspectj/weaver/ltw/.*
- ./aspectjtools1.6.9/org/aspectj/weaver/model/.*
- ./aspectjtools1.6.9/org/aspectj/weaver/patterns/.*
- ./aspectjtools1.6.9/org/aspectj/weaver/reflect/.*
- ./aspectjtools1.6.9/org/aspectj/weaver/tools/.*
- ./aspectjweaver1.6.9/.*
- ./aspectjweaver1.6.9/META-INF/.*
- ./aspectjweaver1.6.9/lib/.*
- ./aspectjweaver1.6.9/org/.*
- ./aspectjweaver1.6.9/org/aspectj/.*
- ./aspectjweaver1.6.9/org/aspectj/apache/.*
- ./aspectjweaver1.6.9/org/aspectj/apache/bcel/.*
- ./aspectjweaver1.6.9/org/aspectj/apache/bcel/classfile/.*
- ./aspectjweaver1.6.9/org/aspectj/apache/bcel/classfile/annotation/.*
- ./aspectjweaver1.6.9/org/aspectj/apache/bcel/generic/.*
- ./aspectjweaver1.6.9/org/aspectj/apache/bcel/util/.*
- ./aspectjweaver1.6.9/org/aspectj/asm/.*
- ./aspectjweaver1.6.9/org/aspectj/asm/internal/.*
- ./aspectjweaver1.6.9/org/aspectj/bridge/.*
- ./aspectjweaver1.6.9/org/aspectj/bridge/context/.*
- ./aspectjweaver1.6.9/org/aspectj/internal/.*
- ./aspectjweaver1.6.9/org/aspectj/internal/lang/.*
- ./aspectjweaver1.6.9/org/aspectj/internal/lang/annotation/.*
- ./aspectjweaver1.6.9/org/aspectj/internal/lang/reflect/.*
- ./aspectjweaver1.6.9/org/aspectj/lang/.*
- ./aspectjweaver1.6.9/org/aspectj/lang/annotation/.*
- ./aspectjweaver1.6.9/org/aspectj/lang/reflect/.*
- ./aspectjweaver1.6.9/org/aspectj/runtime/.*
- ./aspectjweaver1.6.9/org/aspectj/runtime/internal/.*
- ./aspectjweaver1.6.9/org/aspectj/runtime/internal/cflowstack/.*
- ./aspectjweaver1.6.9/org/aspectj/runtime/reflect/.*
- ./aspectjweaver1.6.9/org/aspectj/util/.*
- ./aspectjweaver1.6.9/org/aspectj/weaver/.*
- ./aspectjweaver1.6.9/org/aspectj/weaver/ast/.*
- ./aspectjweaver1.6.9/org/aspectj/weaver/bcel/.*
- ./aspectjweaver1.6.9/org/aspectj/weaver/bcel/asm/.*
- ./aspectjweaver1.6.9/org/aspectj/weaver/internal/.*
- ./aspectjweaver1.6.9/org/aspectj/weaver/internal/tools/.*
- ./aspectjweaver1.6.9/org/aspectj/weaver/loadtime/.*
- ./aspectjweaver1.6.9/org/aspectj/weaver/loadtime/definition/.*
- ./aspectjweaver1.6.9/org/aspectj/weaver/ltw/.*
- ./aspectjweaver1.6.9/org/aspectj/weaver/model/.*
- ./aspectjweaver1.6.9/org/aspectj/weaver/patterns/.*
- ./aspectjweaver1.6.9/org/aspectj/weaver/reflect/.*
- ./aspectjweaver1.6.9/org/aspectj/weaver/tools/.*
- ./org.aspectj.matcher-1.6.9/.*
- ./org.aspectj.matcher-1.6.9/META-INF/.*
- ./org.aspectj.matcher-1.6.9/lib/.*
- ./org.aspectj.matcher-1.6.9/org/.*
- ./org.aspectj.matcher-1.6.9/org/aspectj/.*
- ./org.aspectj.matcher-1.6.9/org/aspectj/bridge/.*
- ./org.aspectj.matcher-1.6.9/org/aspectj/bridge/context/.*
- ./org.aspectj.matcher-1.6.9/org/aspectj/util/.*
- ./org.aspectj.matcher-1.6.9/org/aspectj/weaver/.*
- ./org.aspectj.matcher-1.6.9/org/aspectj/weaver/ast/.*
- ./org.aspectj.matcher-1.6.9/org/aspectj/weaver/internal/.*
- ./org.aspectj.matcher-1.6.9/org/aspectj/weaver/internal/tools/.*
- ./org.aspectj.matcher-1.6.9/org/aspectj/weaver/patterns/.*
- ./org.aspectj.matcher-1.6.9/org/aspectj/weaver/reflect/.*
- ./org.aspectj.matcher-1.6.9/org/aspectj/weaver/tools/.*
